name: dantheman
favicon: null
layout_spectrum: 0.273788723628968
typography_spectrum: 0.10847136867232621
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9562939810566604
  lightness: 0.19990479643456638
  saturation: 0.8591148378327489
  rhythmicContrast: 0.3962790409568697
purpose: []
